# Generated by Django 4.1.3 on 2022-11-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staticpro1',
            new_name='statt_staticpro1',
        ),
    ]
