# Generated by Django 4.1.3 on 2022-11-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statt', '0002_rename_staticpro1_statt_staticpro1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statt_staticpro1',
            new_name='staticpro1',
        ),
    ]
