# Generated by Django 4.1.3 on 2022-11-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statt', '0003_rename_statt_staticpro1_staticpro1'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
    ]
